#version 460 core
layout(local_size_x = 8, local_size_y = 8) in;

layout(rgba32f, binding = 0) uniform image2D imageOut;

uniform vec2 _mouse_position;

void main() {
  ivec2 gidx = ivec2(gl_GlobalInvocationID.xy);
  vec2 size = imageSize(imageOut);
  vec2 uv = vec2(gidx) / size;

  vec4 color = vec4(uv, 0.0, 1.0); // RGB color based on uv coordinates

  imageStore(imageOut, gidx, color * _mouse_position.x / 1300);
}